function createfigure(X1, YMatrix1, X2, YMatrix2)
%CREATEFIGURE(X1, YMatrix1, X2, YMatrix2)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  X2:  vector of x data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 31-May-2020 09:39:31

% Create figure
figure('Color',[1 1 1]);

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',2.5);
set(plot1(1),'DisplayName','E_0=5.00153');
set(plot1(2),'DisplayName','E_1=15.0268');
set(plot1(3),'DisplayName','E_2=25.2065');

% Create multiple lines using matrix input to plot
plot2 = plot(X2,YMatrix2,'LineWidth',2.5);
set(plot2(1),'DisplayName','\phi_0');
set(plot2(2),'DisplayName','\phi_1');
set(plot2(3),'DisplayName','\phi_2');

% Create ylabel
ylabel('Wave functions, Rescaled potential');

% Create xlabel
xlabel('x');

box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',19);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'NumColumns',2);

